name: Discord Announcement

on:
  workflow_run:
    workflows: ["Create Release"]
    types: [completed]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true

jobs:
  discord_announcement:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Read release notes
        id: notes
        run: |
          body="$(cat RELEASE.md)"
          echo "::set-output name=message::$(echo "${body}" | base64 -w0)"
      - name: Get tag name
        id: tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
      - name: Decode notes
        id: decode
        run: |
          echo "::set-output name=text::$(echo '${{ steps.notes.outputs.message }}' | base64 --decode)"
      - name: Send message to Discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: Fleetbase
          content: |
            @everyone
            📦 **Fleetbase ${{ steps.tag.outputs.tag }} released!**

            ${{ steps.decode.outputs.text }}

            [View full notes on GitHub](https://github.com/fleetbase/fleetbase/releases/tag/${{ steps.tag.outputs.tag }})