name: Discord Announcement

on:
  workflow_run:
    workflows: ["Create Release"]
    types: [completed]

  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to announce (e.g. v0.7.1)"
        required: true

jobs:
  discord_announcement:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣  Figure out which tag we’re talking about
    - id: vars
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          TAG="${{ github.event.inputs.tag }}"
        else
          TAG="${{ github.event.workflow_run.head_branch }}"
        fi
        echo "TAG=$TAG"   >> "$GITHUB_ENV"

    # 2️⃣  Check out the exact commit for that tag
    - uses: actions/checkout@v3
      with:
        ref: ${{ env.TAG }}
        fetch-depth: 1          # we only need this one commit

    # 3️⃣  Stash RELEASE.md in an env var (one atomic write → no EOF error)
    - id: notes
      shell: bash
      run: |
        # Trim to 1900 chars so Discord never rejects the message
        body=$(<RELEASE.md)
        [[ ${#body} -gt 1900 ]] && body="${body:0:1900}…"
        {
          printf 'RELEASE_BODY<<EOF\n%s\nEOF\n' "$body"
        } >> "$GITHUB_ENV"

    # 4️⃣  Fire the webhook
    - uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        username: Fleetbase
        content: |
          @everyone
          📦 **Fleetbase ${{ env.TAG }} released!**

          ${{ env.RELEASE_BODY }}

          <https://github.com/${{ github.repository }}/releases/tag/${{ env.TAG }}>