name: Discord Announcement

on:
  workflow_run:
    workflows: ["Create Release"]
    types: [completed]

  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to announce (e.g. v0.7.1)"
        required: true

jobs:
  discord_announcement:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Resolve which tag we’re talking about
    - id: vars
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "tag=${{ github.event.inputs.tag }}" >> "$GITHUB_OUTPUT"
        else
          echo "tag=${{ github.event.workflow_run.head_branch }}" >> "$GITHUB_OUTPUT"
        fi

    # 2️⃣ Check out the exact commit that tag points to
    - uses: actions/checkout@v3
      with:
        ref: ${{ steps.vars.outputs.tag }}
        fetch-depth: 1

    # 3️⃣ Store RELEASE.md as a *multi-line* output, using heredoc syntax
    - id: notes
      run: |
        echo "body<<EOF" >> "$GITHUB_OUTPUT"
        cat RELEASE.md >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

    # 4️⃣ Post to Discord
    - uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        username: Fleetbase
        content: |
          @everyone
          📦 **Fleetbase ${{ steps.vars.outputs.tag }} released!**

          ${{ steps.notes.outputs.body }}

          <https://github.com/${{ github.repository }}/releases/tag/${{ steps.vars.outputs.tag }}>