name: Publish Fleetbase Docker Images

on:
  push:
    tags:
      - 'v*' # Runs on version tags like v1.2.3
  workflow_dispatch: # Allows manual run

jobs:
  docker-release:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    env:
      REGISTRY: fleetbase
      VERSION: ${{ github.ref_name || 'manual' }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Console & API Images
        uses: docker/bake-action@v2
        with:
          push: true
          targets: |
            fleetbase-console
            fleetbase-api
          files: |
            ./docker-bake.hcl